version: 2

project_name: pgroll

before:
  hooks:
    - go mod tidy
    - mkdir -p completions
    - sh -c "go run . completion bash > completions/pgroll.bash"
    - sh -c "go run . completion zsh > completions/pgroll.zsh"

builds:
  - id: pgroll
    binary: pgroll
    flags:
      - -tags=netgo,osusergo
    ldflags:
      - -s -w -X github.com/xataio/pgroll/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
          - CGO_LDFLAGS=-static
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CGO_LDFLAGS=-static
      - goos: darwin
        goarch: amd64
        env:
          - CC=o64-clang
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

nfpms:
  - id: pgroll-deb
    package_name: pgroll
    ids:
      - pgroll
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: "https://github.com/osiris-ratings/pgroll"
    description: "Postgres zero-downtime migrations made easy (Baselayer fork)"
    maintainer: "Blake Watters <blake@baselayer.com>"
    license: "Apache-2.0"
    vendor: "Baselayer"
    formats:
      - deb
    bindir: /usr/bin
    dependencies:
      - curl
      - jq
      - ca-certificates
    contents:
      - src: ./completions/pgroll.bash
        dst: /usr/share/bash-completion/completions/pgroll
        file_info:
          mode: 0644
      - src: ./completions/pgroll.zsh
        dst: /usr/share/zsh/site-functions/_pgroll
        file_info:
          mode: 0644
      - src: ./scripts/pgroll-update.sh
        dst: /usr/local/bin/pgroll-update
        file_info:
          mode: 0755

brews:
  - repository:
      owner: osiris-ratings
      name: pgroll
    directory: Formula
    homepage: "https://github.com/osiris-ratings/pgroll"
    description: "Postgres zero-downtime migrations made easy"
    license: "Apache-2.0"
    custom_require: custom_download_strategy
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    install: |
      bin.install "pgroll"
    test: |
      system "#{bin}/pgroll", "--version"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: osiris-ratings
    name: pgroll
