# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Pgroll < Formula
  desc "Postgres zero-downtime migrations made easy"
  homepage "https://github.com/osiris-ratings/pgroll"
  version "0.16.2-baselayer.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/osiris-ratings/pgroll/releases/download/v0.16.2-baselayer.6/pgroll_0.16.2-baselayer.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "af923ca8bf04651fbcd4bfea407d900f2bb089f05e9f18f7f608cb0deafaae5d"

      define_method(:install) do
        bin.install "pgroll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/osiris-ratings/pgroll/releases/download/v0.16.2-baselayer.6/pgroll_0.16.2-baselayer.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "50bce29ed924d7ee6526a187e1ef97890f3121f3c2de701a7fe31f91fc4f0e94"

      define_method(:install) do
        bin.install "pgroll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/osiris-ratings/pgroll/releases/download/v0.16.2-baselayer.6/pgroll_0.16.2-baselayer.6_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "885421ba50a70195730f2eeb84ef5f84ba6ccfa4b35b7c46c17ee0b3cc9cbf37"
      define_method(:install) do
        bin.install "pgroll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/osiris-ratings/pgroll/releases/download/v0.16.2-baselayer.6/pgroll_0.16.2-baselayer.6_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8ddea79c7e57904aa99b8359eab050df03733a6e2bc500228dbffbe9303f4c17"
      define_method(:install) do
        bin.install "pgroll"
      end
    end
  end

  test do
    system "#{bin}/pgroll", "--version"
  end
end
