name: Build
on:
  pull_request:
  push:
    branches:
      - baselayer
permissions:
  contents: read
jobs:
  cross-build:
    name: cross-platform build
    runs-on: ubuntu-24.04
    container:
      image: goreleaser/goreleaser-cross:v1.24
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      # Mark the checkout as 'safe' despite being owned by `root`
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE 

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'v2.5.1'
          args: build --snapshot

      - uses: actions/upload-artifact@v4
        with:
          name: platform-binaries
          path: dist/
          if-no-files-found: error

  test:
    name: 'test (pg: ${{ matrix.pgVersion }}, schema: ${{ matrix.testSchema }})'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        pgVersion: ['14.8', '15.3', '16.4', '17.0', '18.0', 'latest']
        testSchema: [ 'public', 'non_public' ]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Run tests
      run: go test -cover -coverprofile=coverage.out ./...
      env:
        POSTGRES_VERSION: ${{ matrix.pgVersion }}
        PGROLL_TEST_SCHEMA: ${{ matrix.testSchema }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      if: matrix.pgVersion == 'latest' && matrix.testSchema == 'public'
      with:
        name: code-coverage
        path: coverage.out

  lint:
    name: lint
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        args: --timeout=30m --config=.golangci.yml

  format:
    name: format
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install gofumpt tool
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Run make format
        run: |
          chmod 666 pkg/state/init.sql
          make format

      - name: Ensure code is formatted
        run: |
          if ! git diff --quiet; then
            echo "code formatting is out-of-date!"
            echo "run 'make format' to reformat"
            exit 1
          fi

  coverage:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - uses: fgrosse/go-coverage-report@v1.2.0
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.out"
          root-package: "github.com/xataio/pgroll"

  code-generation:
    name: code generation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Generate code
        run: |
          chmod 666 pkg/state/init.sql
          make generate

      - name: Ensure generated code is up-to-date
        run: |
          if ! git diff --quiet; then
            echo "generated code is out of date!"
            echo "run 'make generate' to regenerate"
            exit 1
          fi

  check-ledger:
    name: check ledger
    runs-on: ubuntu-24.04
    steps:
     - uses: actions/checkout@v4

     - name: Generate ledger
       run: |
         make ledger

     - name: Ensure ledger is up to date
       run: |
         if ! git diff --quiet; then
           echo "generated ledger is out of date!"
           echo "run 'make ledger' to regenerate the ledger"
           exit 1
         fi
         
  dead-code-check:
    name: dead code check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install deadcode tool
        run: |
          go install golang.org/x/tools/cmd/deadcode@latest

      - name: Run deadcode analysis
        run: |
          deadcode --test ./... > deadcode.out
          if [ -s deadcode.out ]; then
            echo "Dead code analysis found the following dead code:"
            cat deadcode.out
            exit 1
          fi

  license-check:
    name: license check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Ensure .go files have a license reference
        run: |
          make license && [[ -z `git status -s` ]]

  examples:
    name: 'examples (pg: ${{ matrix.pgVersion }}, schema: ${{ matrix.testSchema }})'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        pgVersion: ['14.8', '15.3', '16.4', '17.0', '18.0', 'latest']
        testSchema: [ 'public', 'non_public' ]
    services:
      postgres:
        image: postgres:${{ matrix.pgVersion }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Run example migrations
      run: |
        if [ "$PGROLL_SCHEMA" != "public" ]; then
          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U postgres -c "CREATE SCHEMA $PGROLL_SCHEMA;"
        fi

        make examples
      env:
        POSTGRES_PORT: 5432
        POSTGRES_HOST: localhost
        PGPASSWORD: postgres
        PGROLL_SCHEMA: ${{ matrix.testSchema }}

