name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-24.04
    container:
      image: goreleaser/goreleaser-cross:v1.24
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
